services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8081:8080"
